dist: bionic
addons:
  artifacts:
    branch: master
    paths:
      - $(ls out/node-v${BLD_NODE_VERSION}/node-*.tar.gz | tr "\n" ":")
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - curl
      - g++-6
      - gcc-6
      - gcc-6-multilib
      - g++-6-multilib
      - make
      - python
      - ccache
      - xz-utils
env:
  global:
    - CROSSTOOLS_HOME="${HOME}/crosstools"
    - BLD_NODE_VERSION="15.6.0"
    - ARTIFACTS_TARGET_PATHS="/${TRAVIS_REPO_SLUG}/${BLD_NODE_VERSION}"
  jobs:
    - BLD_TARGET_ARCH="armv6l"
    - BLD_TARGET_ARCH="armv7l"
install:
  - set -e
  - git clone --depth 1 https://github.com/lightsourceengine/crosstools.git "${CROSSTOOLS_HOME}"
script:
  - ./scripts/build-arm.sh
