name: build-arm-workflow

on:
  push:
    branches:
      - master

jobs:
  build-arm-job:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[ci skip]') == false
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        arch: [armv6l, armv7l]
    steps:
      - name: Checkout custom-node-builds
        uses: actions/checkout@v2
        with:
          path: main

      - name: Linux Packages
        run: |
          sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
          sudo apt-get update
          sudo apt-get install -y curl g++-8 gcc-8 gcc-8-multilib g++-8-multilib make python ccache xz-utils
          sudo ln -s /usr/include/asm-generic /usr/include/asm
        shell: bash

      - name: Get ARM Toolchain
        run: |
          wget https://github.com/lightsourceengine/ci/releases/download/v1.0.0/x64-gcc-8.3.0.tar.xz
          tar -xJf x64-gcc-8.3.0.tar.xz
          echo "${{github.workspace}}/x64-gcc-8.3.0/arm-rpi-linux-gnueabihf/bin" >> $GITHUB_PATH
        shell: bash

      - name: Build
        env:
          BLD_NODE_VERSION: 16.0.0
          BLD_TARGET_ARCH: ${{matrix.arch}}
          BLD_TOOLCHAIN_PREFIX: arm-rpi-linux-gnueabihf
        run: ./main/scripts/build-arm.sh
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: arm-packages
          path: main/out/node-v*/node-*.tar.gz
