name: build-arm-workflow

on:
  push:
    branches:
      - master

jobs:
  build-arm-job:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[ci skip]') == false
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        arch: [armv6l, armv7l]
        script: [build.sh, build-pi_xnpm_xintl.sh, build-pi_xnpm_xintl_xhttp.sh]
    steps:
      - name: Checkout custom-node-builds
        uses: actions/checkout@v2
        with:
          path: main

      - name: Linux Packages
        run: |
          sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
          sudo apt-get update
          sudo apt-get install -y curl g++-8 gcc-8 gcc-8-multilib g++-8-multilib xz-utils
          sudo ln -s /usr/include/asm-generic /usr/include/asm
        shell: bash

      - name: Get ARM Toolchain
        run: |
          curl https://github.com/lightsourceengine/ci/releases/download/v1.0.0/x64-gcc-8.3.0.tar.xz | tar -xJ
          echo "${{github.workspace}}/x64-gcc-8.3.0/arm-rpi-linux-gnueabihf/bin" >> $GITHUB_PATH
        shell: bash

      - name: Build
        run: main/scripts/${{matrix.script}} ${{matrix.arch}} arm-rpi-linux-gnueabihf 16.0.0
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: arm-packages
          path: node-v*/node-*.tar.gz
