name: build-arm-workflow

on:
  push:
    branches:
      - master

jobs:
  build-arm-job:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[ci skip]') == false
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        arch: [armv6l, armv7l]
    steps:
      - name: Checkout custom-node-builds
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout crosstools
        uses: actions/checkout@v2
        with:
          repository: lightsourceengine/crosstools
          path: crosstools

      - name: Linux Packages
        run: |
          sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
          sudo apt-get update
          sudo apt-get install -y curl g++-6 gcc-6 gcc-6-multilib g++-6-multilib make python ccache xz-utils
          sudo ln -s /usr/include/asm-generic /usr/include/asm
        shell: bash

      - name: Build
        env:
          BLD_NODE_VERSION: 15.14.0
          BLD_TARGET_ARCH: ${{matrix.arch}}
          CROSSTOOLS_HOME: ${{github.workspace}}/crosstools
        run: ./main/scripts/build-arm.sh
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: arm-packages
          path: main/out/node-v*/node-*.tar.gz
